name: recipe_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.7
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  sqflite: ^2.3.3+1
  path: ^1.9.0
  equatable: ^2.0.5
  logger: ^2.4.0
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  uuid: ^4.5.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  custom_lint:
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  flutter_lints: ^4.0.0
  json_serializable: ^6.7.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/foods/
